{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.firebase",
    "module": "firebase-perf-ktx",
    "version": "20.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ngbpehckcfc7tbyodpbqtqnluq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common",
          "version": {
            "requires": "20.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-components",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common-ktx",
          "version": {
            "requires": "20.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf",
          "version": {
            "requires": "20.1.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-perf-ktx-20.1.1-SNAPSHOT.aar",
          "url": "firebase-perf-ktx-20.1.1-SNAPSHOT.aar",
          "size": 19475,
          "sha512": "a976bbe60ba1cfaa401c144034aea70c6f4cba05fff71c2b664e67e93cb099482993e68cdac30c1004e215ca908c57c275174ffadb66c30d58a35d9c28b85396",
          "sha256": "3d167f44e7e58d6e1ec396341d6ea973070fe829750fe8d00c411a1ac5197c4c",
          "sha1": "28f7f4e9f180779cc95a0b8d688da2aac16c383a",
          "md5": "46cf4d0704565d3354db8788204490c4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-perf-ktx-20.1.1-SNAPSHOT.aar",
          "url": "firebase-perf-ktx-20.1.1-SNAPSHOT.aar",
          "size": 19475,
          "sha512": "a976bbe60ba1cfaa401c144034aea70c6f4cba05fff71c2b664e67e93cb099482993e68cdac30c1004e215ca908c57c275174ffadb66c30d58a35d9c28b85396",
          "sha256": "3d167f44e7e58d6e1ec396341d6ea973070fe829750fe8d00c411a1ac5197c4c",
          "sha1": "28f7f4e9f180779cc95a0b8d688da2aac16c383a",
          "md5": "46cf4d0704565d3354db8788204490c4"
        }
      ]
    }
  ]
}
